### ISSUE TITLE
这个如果要重新训练中文模型是不是要几个月的时间。。。

### ISSUE THREAD

**Issue by PeterSaint** [IMLHF/Real-Time-Voice-Cloning#1]

**Comment by IMLHF** [comment]
看你用什么卡了，我用的P40，训encoder大概三四天，sythesizer也差不多

**Comment by PeterSaint** [comment]
我这老显卡估计跑不动。。。

**Comment by PeterSaint** [comment]
请教一下怎么用中文数据集训练_(:з」∠)_

**Comment by IMLHF** [comment]
> 请教一下怎么用中文数据集训练_(:з」∠)_

跟英文的一样，把数据的参数传进去就行了，参考Readme的wiki部分“Training models yourself”
