### ISSUE TITLE
thank u 4 your sharing，would you like to provide a pretained model?

### ISSUE THREAD

**Issue by linghuxinye** [IMLHF/Real-Time-Voice-Cloning#2]

**Comment by IMLHF** [comment]
If you prefer a pre-trained speaker encoder model, I can share it with you. However, the model performance in current stage is not good as I expect.

**Comment by linghuxinye** [comment]
> If you prefer a pre-trained speaker encoder model, I can share it with you. However, the model performance in current stage is not good as I expect.
Thank U for your reply. I have got a speaker encoder model, it's not bad. What troubles me more are SynNet and vocoder.   How about your vocoder model? I'm wondering whether to use speaker embedding for the vocoder. Paper "_**Transfer Learning from Speaker Verification to Multispeaker Text-To-Speech Synthesis**_" and "**_ROBUST UNIVERSAL NEURAL VOCODING_**"  do not use speaker-embedding for wavernn.  I plan to use multilingual data for training it, would you like to give me some advices? Thank U

**Comment by linghuxinye** [comment]
> If you prefer a pre-trained speaker encoder model, I can share it with you. However, the model performance in current stage is not good as I expect.

Thank U for your reply. I have got a speaker encoder model, it's not bad. What troubles me more are SynNet and vocoder. How about your vocoder model? I'm wondering whether to use speaker embedding for the vocoder. Paper "Transfer Learning from Speaker Verification to Multispeaker Text-To-Speech Synthesis" and "ROBUST UNIVERSAL NEURAL VOCODING" do not use speaker-embedding for wavernn. I plan to use multilingual data for training it, would you like to give me some advices? Thank U

**Comment by IMLHF** [comment]
@linghuxinye Baidu research： “Deep Voice 3, Scaling Text-to-Speech with Convolutional Sequence Learning.”

**Comment by geekboood** [comment]
@IMLHF Can you share a link of your trained encoder and synthesizer model?

**Comment by MrZilinXiao** [comment]
@IMLHF A link of your current pretrained model is appreciated! Thanks a lot!
