### ISSUE TITLE
训练效果

### ISSUE THREAD

**Issue by huangx06** [IMLHF/Real-Time-Voice-Cloning#4]
你好，想请教几个问题：
1. speaker encoder 那个模型训练按照你的设置大概需要多少步能出来还不错的效果？我试了5w步。
2. 如果把一个不好的speaker encoder模型用在第二步的syntheser training（这个training需要preprocess的embed（这里用到第一个模型））中，是不是无论syntheser的模型训练多好，都不会达到克隆的效果。
我目前尝试的是第二个合成模型出来还可以，但是没有克隆的效果。
3.有没有什么来评价第一步encoder是否效果已经很好了。第二步的模型可以直接人耳听就可以了，但第一步不知道怎么判断

**Comment by IMLHF** [comment]
我目前也是这个问题，synthesizer可以合成声音，但是没有预期的音色。猜测可能造成这种结果的原因：

**Comment by IMLHF** [comment]
我目前也是这个问题，synthesizer可以合成声音，但是没有预期的音色。猜测可能造成这种结果的原因：1是speaker encoder训练数据不足。2可能是因为synthesizer训练数据质量太差，细节处理不足。目前我正在使用“speaker transfer learning”论文中用到的公开集进行英文的试验，以验证英文多说话人合成是否正常。

**Comment by IMLHF** [comment]
speaker encoder我昨天刚添加了测试集，在训练的时候测试eer，原代码中只有训练集的eer，没什么参考性。如果有需要你也可以测试一下声纹识别的正确率。

**Comment by huangx06** [comment]
感谢，你speaker encoder训练了几步？

**Comment by IMLHF** [comment]
@huangx06 中文的之前用SLR68+aishell2训了300K步。现在刚写出来测试的代码，看看训多少步会过拟合
