### ISSUE TITLE
synthesizer的feeder的inputs输入为什么是二维的？

### ISSUE THREAD

**Issue by leaner1000** [IMLHF/Real-Time-Voice-Cloning#5]
这个应该是拼音转换后的输入向量吧，不应该是[batch_size,sequence_lenth,embed_size]这样3维的吗？

**Comment by leaner1000** [comment]
懂了，好像是不需要转成onehot向量

**Comment by IMLHF** [comment]
embeding是根据id查表后出来的，输入的是id序列
